sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.8.*
  - DJANGO=1.9.*
  - DJANGO=1.10.*
  - DJANGO=1.11.*

before_install:
  - pip install codecov coverage

install:
  - pip install -U Django==$DJANGO
  - pip install -e .[all-filter-dependencies]

script:
  - coverage run runtests.py

after_success:
  - codecov
