sudo: false

language: python

python:
  - 2.7
  - 3.5

env:
  - DJANGO=1.8.*
  - DJANGO=1.9.*
  - DJANGO=1.10.*

#branches:
#  only:
#    - master

before_install:
  - pip install codecov coverage

install:
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO
  - pip install -e .

script: coverage run runtests.py

after_success:
  - codecov
